name: scheduled-update

# Controls when the workflow will run
on:
  schedule:
    - '* * * * *'

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  sync:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Fetch content
        id: content
        run: chmod +x ./scripts/fetch.sh && ./scripts/fetch.sh
      - uses: stefanzweifel/git-auto-commit-action@v4
        id: auto-commit-action
        with:
          commit_message: 'chore(update): 💅 sync content'
          commit_options: '--allow-empty'
          repository: .
          status_options: '--untracked-files=no'
          file_pattern: 'content/day/*.json'
          skip_fetch: true
          disable_globbing: true